[versions]
kotlin = "2.0.20"
ksp = "2.0.20-1.0.24"

jvm = "22"
agp = "8.6.0"

coreKtx = "1.13.1"
composeBom = "2024.08.00"
composeMaterial3 = "1.2.1"
composeActivity = "1.9.1"
composeShimmer = "1.3.1"
composeCoil = "2.7.0"
composeLottie = "6.5.1"

room = "2.6.1"
media3 = "1.4.1"
ktor = "2.3.12"
ktlint = "12.1.1"
detekt = "1.23.6"
detektCompose = "0.4.10"
workmanager = "2.9.1"
credentials = "1.3.0-alpha01"

kotlinCoroutines = "1.8.1"
kotlinDatetime = "0.6.1"
kotlinImmutable = "0.3.7"

brotli = "0.1.2"
palette = "1.0.0"
monet = "0.4.1"

desugaring = "2.1.1"

[plugins]
android_application = { id = "com.android.application", version.ref = "agp" }
android_lint = { id = "com.android.lint", version.ref = "agp" }
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
core_ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

kotlin_coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin_datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDatetime" }
kotlin_immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinImmutable" }

compose_bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose_animation = { module = "androidx.compose.animation:animation" }
compose_foundation = { module = "androidx.compose.foundation:foundation" }
compose_ui = { module = "androidx.compose.ui:ui" }
compose_ui_util = { module = "androidx.compose.ui:ui-util" }
compose_ui_fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose_ripple = { module = "androidx.compose.material:material-ripple" }
compose_material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }

compose_activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose_shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
compose_coil = { module = "io.coil-kt:coil-compose", version.ref = "composeCoil" }
compose_lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "composeLottie" }

room = { module = "androidx.room:room-ktx", version.ref = "room" }
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
exoplayer_workmanager = { module = "androidx.media3:media3-exoplayer-workmanager", version.ref = "media3" }
media3_session = { module = "androidx.media3:media3-session", version.ref = "media3" }

workmanager = { module = "androidx.work:work-runtime", version.ref = "workmanager" }
workmanager_ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }

#noinspection CredentialDependency ==> thank you Android Lint, I added the dependency and this still flags!
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials_play = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }

ktor_http = { module = "io.ktor:ktor-http", version.ref = "ktor" }

ktor_client_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_client_cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor_client_okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor_client_content_negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor_client_encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor_client_serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor_serialization_json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

brotli = { module = "org.brotli:dec", version.ref = "brotli" }
palette = { module = "androidx.palette:palette", version.ref = "palette" }
monet = { module = "com.github.KieronQuinn:MonetCompat", version.ref = "monet" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugaring" }

detekt_compose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
